software-deployment-method: conda
keep-going: true
# rerun-incomplete: true
printshellcmds: true
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 4
latency-wait: 240
jobs: 1000
# remote-job-local-storage-prefix: "/lscratch/\$SLURM_JOB_ID"

default-resources:
  slurm_partition: "ccr,norm"
  cpus_per_task: 4
  mem_mb_per_cpu: 2048
  runtime: 8-00:00:00
  slurm_extra: "'--gres=lscratch:100'"

set-resources:

  bowtie2_host_index:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  kraken2_db:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  kraken2_nucl_read_classif_pe:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  kraken2_nucl_read_classif_se:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  kraken2_prot_read_classif_pe:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  kraken2_prot_read_classif_se:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  krakenuniq_db:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  krakenuniq_read_classif_pe:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  krakenuniq_read_classif_se:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096

  bracken_db:
    cpus_per_task: 56
    mem_mb_per_cpu: 4096
