executor: slurm
software-deployment-method: conda
keep-going: true
rerun-incomplete: true
printshellcmds: true
scheduler: greedy
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 4
latency-wait: 60
jobs: 5000

resources:
  gdc_download_jobs: 10

default-resources:
  slurm_account: hermidalc
  slurm_partition: "ccr,norm"
  cpus_per_task: 2
  mem: "8g"
  runtime: "10d"
  slurm_extra: "'--gres=lscratch:100'"

set-resources:
  host_genome_index:
    cpus_per_task: 56
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  host_filtered_fastq_pe:
    cpus_per_task: 56
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  host_filtered_fastq_se:
    cpus_per_task: 56
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  kraken2_nucl_db_library:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  kraken2_prot_db_library:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  kraken2_db:
    cpus_per_task: 56
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  kraken2_nucl_read_classif_pe:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  kraken2_nucl_read_classif_se:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  kraken2_prot_read_classif_pe:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  kraken2_prot_read_classif_se:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  krakenuniq_db_taxonomy:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  krakenuniq_db_library:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  krakenuniq_db:
    cpus_per_task: 56
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  krakenuniq_read_classif_pe:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  krakenuniq_read_classif_se:
    cpus_per_task: 28
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"

  bracken_db:
    cpus_per_task: 56
    mem: 0
    slurm_extra: "'--exclusive --gres=lscratch:100'"
