name: krakenuniq download
description: Metagenomics classifier with unique k-mer counting for more specific results
authors:
  - Leandro C. Hermida
notes: |
  * For more information see, https://github.com/fbreitwieser/KrakenUniq
