name: kraken2-classify
description: Kraken2 fast taxonomic classification tool for metagenomic sequencing data
authors:
  - Leandro C. Hermida
notes: |
  * For more information see, https://github.com/DerrickWood/kraken2
