---
wrappers:
  public:
    version: v3.13.7
  personal:
    base_url: https://github.com/hermidalc/snakemake-wrappers/raw/main
  local:
    base_url: file:wrappers

random_seed: 777

download:
  retries: 5

resources:
  ref:
    name: T2T-CHM13v2
    fasta_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz
  db:
    name: MicrobialDB
    base_dir: resources/kraken2/db
    libs:
      kraken2:
        names: [archaea, bacteria, viral, human, UniVec_Core]
        nucl_only: [UniVec, UniVec_Core]
        ftp_only: [bacteria]
      krakenuniq:
        names: [refseq/archaea, refseq/bacteria, refseq/viral]
      custom:
          eupathdb:
            base_url: ftp://ftp.ccb.jhu.edu/pub/data/EuPathDB54
            fa_tgz_filename: eupathDB54_CLEAN.tar.gz
            idmap_filename: seqid2taxid_eupathDB54.map
    bracken:
      readlens: [25, 35, 50, 75, 100, 125, 150]

study: tcga_wgs

gdc:
  program_names: [
    'TCGA'
  ]
  sample_types: [
    'Primary Tumor',
    'Primary Blood Derived Cancer - Peripheral Blood',
    'Additional - New Primary'
  ]
  exp_strategy: WGS
  workflow_types: [
    'BWA with Mark Duplicates and BQSR'
  ]
  metadata:
    data_dir: data/gdc
    log_dir: logs/gdc
    subdir: all
    file_meta_filename: gdc_file_meta.tsv
    readgrp_meta_filename: gdc_readgrp_meta.tsv
    uniq_readgrps_filename: gdc_uniq_readgrps.tsv

host_filter:
  mode: hisat2

read_classif:
  mode: kraken2

bowtie2:
    build:
      extra: ''
      threads: all
    align:
      extra: ''
      threads: all

hisat2:
    build:
      extra: ''
      threads: all
    align:
      extra: ''
      threads: all

biobambam2:
  bamtofastq:
    extra:
      common: >-
        exclude=QCFAIL,SECONDARY,SUPPLEMENTARY
        gz=1
        inputformat=bam
        level=5
        tryoq=1
      paired_end: collate=1
      per_readgrp: >-
        outputperreadgroup=1
        outputperreadgroupsuffixF=_unmapped_1.fq.gz
        outputperreadgroupsuffixF2=_unmapped_2.fq.gz
        outputperreadgroupsuffixO=_unmapped_o1.fq.gz
        outputperreadgroupsuffixO2=_unmapped_o2.fq.gz
        outputperreadgroupsuffixS=_unmapped_s.fq.gz

kraken2:
  download:
    use_ftp: false
  k2:
    script_dir: 'external/kraken2/2.1.3-custom/linux-64/scripts'
    extra: ''
    threads: all
    verbosity: 1
  build:
    tsearch_unclassif: true
    extra: ''
    threads: all
  classify:
    extra:
      common: '--use-names'
      paired_end: ''
    threads: all

krakenuniq:
  download:
    use_rsync: true
    extra: ''
    threads: all
  build:
    extra:
    threads: all
  classify:
    extra:
      common: '--preload-size 16G'
      paired_end: '--check-names'
    threads: all

krakentools:
  combine_kreports:
    extra: '--only-combined'

bracken:
  build:
    threads: all
  quant:
    level: S
    threshold: 0.0
