---
wrappers:
  public:
    version: v3.13.7
  personal:
    base_url: https://github.com/hermidalc/snakemake-wrappers/raw/main
  local:
    base_url: file:wrappers

tmp_dir: /tmp

random_seed: 777

download:
  retries: 5

resources:
  ref:
    fasta_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz
  db:
    base_dir: /mnt/hgfs/D/tcga-wgs-kraken-microbial-quant/resources
    kraken2:
      libs: [archaea, bacteria, viral, human, UniVec_Core]
      name: MicrobialDB
    krakenuniq:
      libs: [refseq/archaea, refseq/bacteria, refseq/viral, human, UniVec_Core]
      name: MicrobialDB
    bracken:
      readlens: [25, 35, 50, 75, 100, 125, 150]

study: tcga_wgs

gdc:
  program_names: [
    'TCGA'
  ]
  sample_types: [
    'Primary Tumor',
    'Primary Blood Derived Cancer - Peripheral Blood',
    'Additional - New Primary'
  ]
  exp_strategy: WGS
  workflow_types: [
    'BWA with Mark Duplicates and BQSR'
  ]
  metadata:
    data_dir: data/gdc
    log_dir: logs/gdc
    file_meta_filename: gdc_file_meta.tsv
    readgrp_meta_filename: gdc_readgrp_meta.tsv
    uniq_readgrps_filename: gdc_uniq_readgrps.tsv

host_filter:
  mode: bowtie2

read_classif:
  mode: kraken2

bowtie2:
    build:
      threads: all
    align:
      threads: all

biobambam2:
  bamtofastq:
    extra:
      common: >-
        exclude=QCFAIL,SECONDARY,SUPPLEMENTARY
        gz=1
        inputformat=bam
        level=5
        tryoq=1
      paired_end: collate=1
      per_readgrp: >-
        outputperreadgroup=1
        outputperreadgroupsuffixF=_unmapped_r1.fastq.gz
        outputperreadgroupsuffixF2=_unmapped_r2.fastq.gz
        outputperreadgroupsuffixO=_unmapped_o1.fastq.gz
        outputperreadgroupsuffixO2=_unmapped_o2.fastq.gz
        outputperreadgroupsuffixS=_unmapped_se.fastq.gz

kraken2:
  build:
    extra: '--protein --use-ftp'
    threads: all
  classify:
    extra:
      common: '--use-names'
      paired_end: '--paired'
    threads: all

krakenuniq:
  download:
    extra:
    threads: all
  build:
    extra:
    threads: all
  classify:
    extra:
      common: '--preload-size 16G'
      paired_end: '--paired --check-names'
    threads: all

bracken:
  build:
    threads: all
  quant:
    level: S
    threshold: 0.0
