---
wrapper:
  public:
    version: v3.13.6
  personal:
    base_url: https://github.com/hermidalc/snakemake-wrappers/raw/main/

tmp_dir: /tmp

random_seed: 777

download:
  retries: 5

resources:
  ref:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/
    filename: GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz
    dir: resources/chm13

study: tcga_wgs

input:
  mode: gdc
  gdc:
    token: ''
    program_names: ['TCGA']
    sample_types: [
      'Primary Tumor',
      'Primary Blood Derived Cancer - Peripheral Blood',
      'Additional - New Primary'
    ]
    exp_strategy: WGS
    workflow_types: ['BWA with Mark Duplicates and BQSR']

host_filter:
  mode: bowtie2

bowtie2:
    build:
      threads: all
    align:
      threads: all

samtools:
  fastq:
    # exclude secondary alignments
    # output compressed fastq.gz
    extra: '-F 256 -c 6'
    threads: all
