---
wrappers:
  public:
    version: v3.13.6
  personal:
    base_url: file:wrappers

tmp_dir: /tmp

random_seed: 777

download:
  retries: 5

resources:
  ref:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/
    filename: GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz
  krakenuniq:
    microbialdb:
      dir: /mnt/hgfs/VMData/salzberg/resources/MicrobialDB

study: tcga_wgs

input:
  mode: gdc
  gdc:
    token: ''
    program_names: [
      'TCGA'
    ]
    sample_types: [
      'Primary Tumor',
      'Primary Blood Derived Cancer - Peripheral Blood',
      'Additional - New Primary'
    ]
    exp_strategy: WGS
    workflow_types: [
      'BWA with Mark Duplicates and BQSR'
    ]
    meta_file: data/gdc/gdc_bam_meta.tsv

host_filter:
  mode: bowtie2

bowtie2:
    build:
      threads: all
    align:
      threads: all

samtools:
  sort:
    # important sort by read name
    extra: '-n'
    threads: all
  fastq:
    # exclude secondary alignments
    # output compressed fastq.gz
    extra: '-F 256 -c 6'
    threads: all

krakenuniq:
  extra: '--preload-size 16G --check-names'
  threads: all

bracken:
  level: S
  threshold: 0
  extra: ''
  threads: all
